vim.keymap.set("n", "<leader>gs", vim.cmd.Git)
vim.keymap.set("n", "<leader>gb", function () vim.cmd.Git('blame') end)
vim.keymap.set("n", "<leader>gl", function () vim.cmd.Git('pull') end)
vim.keymap.set("n", "<leader>gp", function () vim.cmd.Git('push') end)
vim.keymap.set("n", "<leader>glg", function () vim.cmd.Git('log') end)
vim.keymap.set("n", "<leader>gpv", function () vim.cmd.Git('co -') end)
